import type { PlanetName, SignName } from "@/game/types";

// Original placement portraits informed by spec/concept/PLANET_MATRIX.md.
// Read each planet's framework and placement notes when revising its copy.
// These introductions are separate from the sourced planetary chorus.
export const PLANET_INTRODUCTIONS: Record<PlanetName, Record<SignName, string>> = {
  Sun: {
    Aries: "You come alive in the moment of beginning. You may not know what waits beyond the door, but there is something unmistakably yours in the hand that opens it.",
    Taurus: "The things you tend begin to carry your presence. In a garden that returns each year, or a table worn smooth with use, you recognize the life you have made.",
    Gemini: "You discover yourself in the exchange between one mind and another. Someone asks a question you have never considered, and your own answer surprises you.",
    Cancer: "You remember how they take their tea, though they have been away for years. Something of who you are lives in that care, in the cup you still keep ready.",
    Leo: "You want to put something of yourself into the world. When you share what you have made, the pleasure you took in making it can warm the whole room.",
    Virgo: "You recognize yourself in the care of a well-made thing. There is satisfaction in the small adjustment that lets it work, and in knowing when your work is done.",
    Libra: "You come to know your own mind by listening to another. Fairness matters enough to you that you will sometimes disturb an easy agreement to make room for an unheard voice.",
    Scorpio: "You want to know what is true beneath the appearance. When a conversation reaches what no one wants to name, you can stay long enough for honesty to become possible.",
    Sagittarius: "An unfamiliar idea can make your whole life feel larger overnight. You want to follow it far enough to return with a story worth telling.",
    Capricorn: "You return to the work long after anyone has thought to praise it. What you are building has a meaning you do not need to announce.",
    Aquarius: "You can imagine a way of living together that has no place yet. Giving the idea a voice feels like introducing a part of yourself, and inviting others to help it take shape.",
    Pisces: "A feeling can reach you before you have words for it. Sometimes a melody gives it a shape, and you recognize something of yourself that an ordinary description would have missed.",
  },
  Moon: {
    Aries: "Your feelings arrive with a wish to move. A window thrown open, a quickened step: sometimes your body finds an answer before you can explain what you need.",
    Taurus: "Familiar comforts help you settle back into yourself. The room grows quiet, the bread is cooling, and for a moment there is enough in being here.",
    Gemini: "You begin by describing your day. Somewhere in the telling, a feeling you had scarcely noticed finds its name, and you understand why you wanted company.",
    Cancer: "A familiar voice can reach a place in you that argument cannot. An old lullaby brings back the lamplight of a remembered room, and the feeling of being safe there.",
    Leo: "Your delight is difficult to keep to yourself. A welcome called across the room, answered with equal warmth, can make you feel at home before you have taken off your coat.",
    Virgo: "Putting one small thing in order helps you breathe. A cleared table or a carefully folded cloth can give you a little peace when your feelings are harder to arrange.",
    Libra: "You feel the ease between people as a comfort of your own. A conversation that softens into companionable silence can stay with you long after you have gone home.",
    Scorpio: "There are feelings you do not offer lightly. With someone who lets you keep your own pace, you may find yourself saying what you had meant to keep private.",
    Sagittarius: "Your spirits lift when the familiar streets give way to somewhere new. You can return from a walk with a little more room around the feeling that sent you out.",
    Capricorn: "You know how to remain composed when someone needs you. There is relief in a place where you can finally take off your coat and let that effort rest.",
    Aquarius: "You can relax among people who do not need you to resemble them. An empty chair among friends can hold the promise of company and the freedom to remain yourself.",
    Pisces: "Other people's moods can stay with you after they have left. With the curtains drawn and a little quiet, you begin to recognize which feelings are your own.",
  },
  Mercury: {
    Aries: "You find the words that get a stalled conversation moving. A direct question comes readily to you, often while everyone else is still deciding how to begin.",
    Taurus: "You want to see how an idea holds up in use. Turn it over, try it in your hands, and the explanation comes in words as plain as the thing itself.",
    Gemini: "One answer gives you several new questions. You notice when two conversations belong together, and enjoy being the one who carries an idea from one to the other.",
    Cancer: "You remember the pause as clearly as the words. The way someone tells a story can stay with you for years, carrying a meaning the bare account would lose.",
    Leo: "You know where a story comes alive. A gesture, a well-timed pause, and the people listening can feel why it mattered so much to you.",
    Virgo: "You notice the detail that changes the answer. There is pleasure in finding the exact word or the missing step that makes a tangled explanation clear.",
    Libra: "You can restate a disagreement so each person recognizes their own concern. Your gift for comparison lets a conversation continue where it might otherwise have ended.",
    Scorpio: "The first explanation leaves something unanswered. You keep the question in mind until a small inconsistency reveals the cause beneath the stated reason.",
    Sagittarius: "You want to know where an idea leads. A fact becomes memorable when it connects distant places or changes the larger story you are trying to understand.",
    Capricorn: "You can turn a complicated intention into the next few things to do. Your explanations have room for a dry remark, then return to the point.",
    Aquarius: "You notice an assumption everyone else has stopped seeing. Move it out of the way, and a problem that seemed settled may admit a wholly different answer.",
    Pisces: "An image comes to mind before the explanation does. You search for a comparison until someone else can see what you understood before you had the words.",
  },
  Venus: {
    Aries: "You do not always wait for the perfect moment to show affection. The unexpected invitation, the gift chosen on impulse: sometimes your willingness makes the moment.",
    Taurus: "You take pleasure in the weight of a cup and the warmth of someone's hand. Affection has time to settle when a meal is good and neither of you is in a hurry.",
    Gemini: "You remember the strange question that made you both laugh. Wanting to hear their next thought can be the first sign that someone has become dear to you.",
    Cancer: "You keep the small thing they gave you long after its practical use has passed. It still carries the moment of being thought of, and the tenderness of a shared history.",
    Leo: "You want the people you love to know how gladly you have chosen them. Sometimes an ordinary evening becomes an occasion because you have found a new way to say so.",
    Virgo: "You remember what would make their day a little easier. A task quietly taken over can carry an affection you might find awkward to announce.",
    Libra: "You enjoy the small decisions that make room for two. Choosing flowers together, or finding a song you both love, can make affection feel easy to express.",
    Scorpio: "What draws you closer is often what someone rarely shows. Being trusted with a private fear or an unguarded wish makes your affection more attentive.",
    Sagittarius: "You like discovering how someone meets a world neither of you knows. An unfamiliar road or a meal shared far from home gives you something new to love about them.",
    Capricorn: "You notice who keeps showing up. In time, a small promise kept can mean as much to you as a declaration, and you offer that same constancy in return.",
    Aquarius: "Someone's unusual way of seeing things may be what first draws you close. Affection can grow from a friendship in which neither of you has to become more ordinary.",
    Pisces: "You can be moved by a beauty others pass over. An imperfect gift becomes precious through the feeling behind it, and you are inclined to look at people with that same tenderness.",
  },
  Mars: {
    Aries: "Once you see what needs doing, your hands are ready to begin. The first attempt brings a satisfaction of its own, especially when the obstacle has made everyone hesitate.",
    Taurus: "Your effort finds a pace it can keep. Day after day, another row is finished, and what first seemed too much begins to yield to your persistence.",
    Gemini: "When the first approach stalls, another occurs to you. An improvised tool or a different route can restore your appetite for the attempt.",
    Cancer: "Your resolve gathers around what you care for. A damaged shelter or someone in need can give you a clear reason to act, even when your own wishes feel uncertain.",
    Leo: "You want to put your heart into what you attempt. There is pleasure in the bold gesture and the wholehearted effort, even in a rehearsal with no one watching.",
    Virgo: "You see where to adjust the tool or change the order of the work. Applied patiently, that attention turns a difficult undertaking into steps your hands know how to do.",
    Libra: "You notice who would bear the cost of a decision. The wish for a fair outcome can bring you back to a stalled discussion with the resolve to see it through.",
    Scorpio: "You can hold your effort quietly through a difficult undertaking. Long after the first excitement has passed, you are still working at the knot that others have set aside.",
    Sagittarius: "An inviting possibility makes you want to be on your way. The pack is ready, and the first mile gives your enthusiasm somewhere to go.",
    Capricorn: "You can divide a distant undertaking into work that fits today. There is satisfaction in laying the foundation carefully, knowing what it will have to carry.",
    Aquarius: "You are willing to try the method no one has made room for yet. A familiar tool put to an unexpected use can be the beginning of a change you want to see.",
    Pisces: "You may begin because an image will not leave you alone. Making one small part of it real gives the feeling a direction, and a reason to return.",
  },
  Jupiter: {
    Aries: "You discover what is possible by trying it firsthand. An unfamiliar skill attempted in earnest can give you more confidence than another assurance that you are ready.",
    Taurus: "There is pleasure in seeing patient care become abundance. A garden with enough to give away lets you enjoy what you have grown, and imagine who might share it.",
    Gemini: "An ordinary conversation can send you toward a subject you had never considered. Your curiosity makes even a borrowed book feel like the beginning of a larger life.",
    Cancer: "You can make a gathering feel as though there was always room for one more. A larger circle begins with another place at the table and the welcome you offer.",
    Leo: "Your enthusiasm can make someone else's idea feel worth attempting. You enjoy the moment they grow bolder, and are often ready with the first encouragement.",
    Virgo: "You believe in improvement because you have watched it happen in small ways. Passing on a useful skill lets the care you have taken become a possibility for someone else.",
    Libra: "You notice when two people could help each other. Bringing them together gives you pleasure in an opportunity that neither would have found alone.",
    Scorpio: "You are willing to follow a question into an uncomfortable answer. What you discover can unsettle an old belief and leave you with a fuller understanding to live by.",
    Sagittarius: "You want an experience that gives you more to think about on the way home. A journey through another place or another belief can change what you thought was possible.",
    Capricorn: "You recognize the small beginning that might support something larger. Giving it time and structure is one way you express belief in a future you can help build.",
    Aquarius: "You are interested in what a new idea could make possible for many people. A discovery feels more promising when the workshop is open and others can take part.",
    Pisces: "A small kindness can restore your sense that more is possible. You carry the feeling into your next encounter, a little readier to see what might be good there.",
  },
  Saturn: {
    Aries: "You take the responsibility of beginning seriously. Even with uncertainty close at hand, there is a quiet authority in choosing a first step and standing behind it.",
    Taurus: "You know the reassurance of keeping something in reserve. The stores you have patiently gathered can offer a quieter pleasure when you recognize there is enough to put them to use.",
    Gemini: "You take care with what you say because you want it to hold up. A sentence revised until it is accurate can give you the confidence to speak.",
    Cancer: "You may be accustomed to making sure everyone else is settled. Being the one someone makes a place for can feel unfamiliar, and deeply welcome.",
    Leo: "You return to the passage until your hands know it. Taking your creative work seriously can give you a steadiness that remains when the audience has gone.",
    Virgo: "You have patience for the details that others leave unfinished. There is a particular satisfaction in signing off on work that has received the care you know it needed.",
    Libra: "You take seriously what people owe one another. An agreement made with care, and honored over time, gives a relationship something both people can trust.",
    Scorpio: "You understand the weight of a confidence, and can keep it for years. Someone who entrusts you with a difficult truth may find a patience they had not expected.",
    Sagittarius: "You want a belief that can bear the weight you place on it. The book you return to gathers notes in the margins as experience gives you new questions.",
    Capricorn: "You understand what it takes to keep something standing. In the work of maintaining it over years, responsibility becomes a craft you can pass into another pair of hands.",
    Aquarius: "You want a good idea to survive beyond the people who first proposed it. Patient work gives a shared hope a form that others can help maintain.",
    Pisces: "You can give a dream a regular place in your day. An hour set aside for making lets something once elusive become a part of life you can return to.",
  },
};
