import type { PlanetName, SignName } from "@/game/types";

// Original placement portraits, separate from the sourced planetary chorus.
// Each planet describes its own domain of the self, expressed through a sign.
export const PLANET_INTRODUCTIONS: Record<PlanetName, Record<SignName, string>> = {
  Sun: {
    Aries: "You find yourself by taking the first step. There is a kind of courage in beginning before anyone has given you permission. Once the first excitement passes, staying with what you started asks something quieter of you.",
    Taurus: "You come to know yourself through what you can touch and tend. A life built slowly feels like a life that is yours. When something familiar stops nourishing you, it can take time to loosen your grip.",
    Gemini: "You discover who you are in conversation. An unfamiliar idea can bring out a self you hadn’t met before. Keeping every possibility open can make it hard to say where you stand.",
    Cancer: "Your sense of self takes shape around what you care for. You remember what others forget, and make a home of what you love. Sometimes, holding on feels safer than letting life change.",
    Leo: "You want to put something of yourself into the world and see it answered. Your warmth can make others feel more fully themselves. Being overlooked hurts, especially when you’ve offered something heartfelt.",
    Virgo: "You recognize yourself in the care you bring to a thing. Making something work a little better gives you a quiet sense of purpose. There is always another flaw to find, including in work that already deserves your pride.",
    Libra: "You discover yourself in the presence of another. Making room for a different point of view comes naturally to you. Sometimes you can see everyone’s position so clearly that your own becomes difficult to name.",
    Scorpio: "You want a life that feels true beneath the surface. You can stay with difficult feelings long enough to discover what they conceal. Letting yourself be known may feel more exposing than understanding someone else.",
    Sagittarius: "You feel most yourself when your world is opening. A distant place or an unfamiliar belief can give your life a new direction. The next horizon is inviting; the life already around you asks for attention too.",
    Capricorn: "You come to trust yourself through what you build and sustain. There is satisfaction in becoming someone others can depend on. You may find it harder to believe you deserve care when you have nothing to offer.",
    Aquarius: "You recognize yourself in the possibility of doing things differently. A place among people who share your hopes can matter more than fitting in. Protecting your independence can make it difficult to admit how much you need that place.",
    Pisces: "Your sense of self has room for dreams and feelings that are difficult to name. You can enter another person’s world with unusual tenderness. Returning to your own wishes takes practice when so much reaches you.",
  },
  Moon: {
    Aries: "Your feelings arrive quickly and ask to move. Taking a small action can settle you more than a long explanation. The feeling may pass before the people around you have caught up with its force.",
    Taurus: "You settle into familiar comforts: a meal made well, a room that feels like yours. Repeated acts of care help you trust that you are safe. A change in those small rituals can unsettle you more than you expect.",
    Gemini: "You often discover what you feel by talking about it. Finding a name for your inner weather gives you room to breathe. Sometimes the explanation comes easily while the feeling itself still needs time.",
    Cancer: "You carry an inner home made of remembered voices and small gestures. Caring for someone can soothe you as much as being cared for. Old hurts can remain close, even after the room around you has changed.",
    Leo: "Your heart settles when affection is expressed freely. A little warmth or delight can restore more than someone might guess. When care goes unspoken, you may struggle to feel the love that is still there.",
    Virgo: "Putting a room in order can help you put a feeling in order. You offer comfort through useful, attentive acts. Some days you need care that asks nothing of you, including an explanation of what is wrong.",
    Libra: "You feel the atmosphere between people keenly. An easy exchange can settle you; an unresolved disagreement can follow you home. Keeping the peace sometimes leaves your own discomfort without a place to go.",
    Scorpio: "You need somewhere your strongest feelings can be received without alarm. Once you trust someone, your attachment runs deep. Waiting for proof that it is safe to open up can become a long, lonely vigil.",
    Sagittarius: "Space helps you recover your spirits. A walk beyond your usual route can remind you that a difficult feeling is not the whole world. Some sadness needs your company before a change of scene can help.",
    Capricorn: "You steady yourself by attending to what needs doing. Being reliable can feel safer than letting someone see you need help. There is room for the part of you that wants to be held without having earned it.",
    Aquarius: "A little distance helps you understand what is happening inside. You may find comfort among friends who give you room to be unusual. Explaining a feeling from afar does not always satisfy the part of you living through it.",
    Pisces: "The mood of a room can follow you long after you leave. Solitude, music, or a little time to dream helps you return to yourself. You may need to set down a sorrow before you know whether it was yours.",
  },
  Mercury: {
    Aries: "Your mind likes a clear opening and a direct answer. You can say the thing everyone else is still circling. Giving an unfinished thought another moment may reveal something your first certainty missed.",
    Taurus: "You take an idea in slowly and test it against experience. Once you understand something, you can explain it with reassuring steadiness. A conclusion that served you well may become difficult to reconsider.",
    Gemini: "Your mind follows the thread from one thing to another. You hear possibilities in an ordinary exchange and enjoy finding words for them. Finishing one thought can be harder than beginning several interesting ones.",
    Cancer: "You remember how something was said as clearly as the words themselves. Your thinking carries the texture of experience, and your stories can make the past feel close. An old conversation may color a new one before you notice.",
    Leo: "You think best when an idea comes alive in the telling. Your enthusiasm can help others see what makes it worth their attention. It can sting when they question a thought you have put so much of yourself into.",
    Virgo: "You notice where an explanation stops making sense. Patient attention lets you untangle what others have hurried past. The search for the exact word can sometimes keep a useful thought from being spoken at all.",
    Libra: "You can carry more than one side of a question in your mind. Your words often help people hear each other. Reaching a conclusion asks you to accept that a fair decision may still leave someone unconvinced.",
    Scorpio: "You listen for the question beneath the question. A contradiction draws your attention, and you are willing to follow it into uncomfortable territory. Sometimes a simple answer is whole, even when you could keep looking beneath it.",
    Sagittarius: "You think in broad connections and ideas that point somewhere. Your excitement can make a difficult subject feel like an invitation. A small detail may deserve a second look before it becomes part of your larger story.",
    Capricorn: "You want an idea you can put to work. Your mind gives shape to complicated tasks by finding what needs to happen first. An impractical suggestion may need a little freedom before its use becomes clear.",
    Aquarius: "You can step outside a familiar assumption and see another way through. Conversation becomes exciting when it changes the terms of the question. Remembering the person listening helps an unusual idea find somewhere to land.",
    Pisces: "You often grasp a feeling or an image before you find the words. Your mind makes connections that a straight explanation might miss. Translating that understanding for someone else may ask for more precision than the original insight did.",
  },
  Venus: {
    Aries: "Affection brings out your willingness to risk a first move. You enjoy the spark of discovering someone and letting them know. When closeness becomes familiar, desire may ask you to find a new kind of attention.",
    Taurus: "You show love by making it tangible. Time together, a thoughtful meal, or a touch can say what a declaration cannot. Something precious can become difficult to share with change, even when the bond itself remains.",
    Gemini: "You are drawn to people who keep a conversation alive. Curiosity is one of your ways of showing affection: you want to discover someone again. Closeness also has quiet stretches, when neither person has anything new to say.",
    Cancer: "You love through the small things you remember. Making someone feel at home is an intimate act for you. When they need space, it can be difficult to feel that your care still has a place in their life.",
    Leo: "You enjoy giving affection a visible form. A generous gesture can make the person you love feel wonderfully chosen. You want to feel chosen too, and may find it difficult to ask for that without turning it into a test.",
    Virgo: "Love draws your attention to what would make someone’s day easier. You notice the little things and often act before being asked. Offering care becomes gentler when there is room for something to remain imperfect.",
    Libra: "You enjoy the art of being together. A shared pleasure or a thoughtful exchange can make affection feel effortless. Saying what you want is part of intimacy, even when it disturbs a beautiful agreement.",
    Scorpio: "You are drawn to closeness that changes what can be said between two people. Trust makes room for a depth of affection you do not offer lightly. Wanting certainty about a bond can make it difficult to let it breathe.",
    Sagittarius: "Affection grows when there is room to discover the world together. You value a bond that welcomes honesty and leaves the door open to experience. Staying close sometimes means staying for a conversation you would rather outwalk.",
    Capricorn: "You take affection seriously and often express it through lasting commitment. Showing up again can mean more to you than making a grand declaration. Letting someone enjoy your unguarded company is a gift you can give before everything is in order.",
    Aquarius: "Friendship is often the ground on which your affection grows. You want room for each person to remain fully themselves. A bond may ask for particular, personal reassurance even when your commitment feels clear in principle.",
    Pisces: "You are moved by the beauty in someone that they may barely see themselves. Affection makes you tender toward their unfinished parts. It can be difficult to distinguish loving a person from hoping to become the answer to their pain.",
  },
  Mars: {
    Aries: "You meet resistance by moving toward it. The courage to act comes readily when something matters to you. Pausing long enough to choose your direction can make that first surge carry you further.",
    Taurus: "Once you commit, your effort has staying power. You can keep going long after the first excitement has worn off. Changing direction may feel like surrender, even when it would protect what you are working for.",
    Gemini: "You act by finding another angle. A quick question or a change of approach can open a way through resistance. Scattering your effort across every possible route may leave the thing you want just out of reach.",
    Cancer: "Your resolve rises when something you care for needs protecting. You may act decisively for someone else while finding your own wants harder to name. A hurt left unspoken can end up choosing your direction for you.",
    Leo: "You bring heart to what you pursue. A purpose you can be proud of gives your effort warmth and force. Criticism can feel personal when your courage and your work are so closely joined.",
    Virgo: "You turn effort into a sequence of things that can actually be done. Careful adjustments help you make progress through a difficult task. There is a point where further preparation postpones the attempt you are ready to make.",
    Libra: "You want your actions to be fair, and you notice who will bear their consequences. That awareness can make you a thoughtful advocate. Acting on your own behalf may require a decision that everyone does not approve of.",
    Scorpio: "You can hold your effort quietly until the moment to act arrives. A difficult undertaking gives your determination something to grip. Knowing when to release a pursuit can ask more of you than continuing it.",
    Sagittarius: "You find energy in a purpose that reaches beyond your present life. Possibility gives you the courage to attempt more than you know how to do. The ordinary work afterward needs a share of that same enthusiasm.",
    Capricorn: "You can turn a distant aim into work you are willing to do today. Your determination grows through practice and visible progress. Rest may feel like losing ground even when it is what lets you continue.",
    Aquarius: "You find resolve in the possibility that things could be otherwise. Acting with others toward a shared change can bring out your persistence. A cause still needs your patience with the particular people trying to carry it forward.",
    Pisces: "Your energy responds to feeling and imagination. Something that moves you can call forth an effort that obligation alone cannot. Naming what you want helps that energy find a direction you can sustain.",
  },
  Jupiter: {
    Aries: "You grow by trusting yourself enough to begin. An opportunity often becomes real only after you have taken a step toward it. Your confidence opens doors; listening to experience helps you decide which ones to keep entering.",
    Taurus: "You find faith in what grows with patient care. Enough food, enough time, something to share: abundance can be close at hand. Comfort becomes limiting when it leaves no room for an unfamiliar kind of good.",
    Gemini: "Your world grows through questions and chance conversations. Learning a little about something can open an unexpected door. Following one curiosity beyond the first discovery may offer more than collecting another beginning.",
    Cancer: "You find hope in the possibility of making room for someone. Generosity often takes the shape of welcome, and belonging gives you courage. The circle you care for can grow without losing what first made it feel like home.",
    Leo: "You grow when you allow yourself to create and be seen. Your confidence can give others the courage to attempt something of their own. There is also joy in a good thing that happens beyond the reach of your influence.",
    Virgo: "You find meaning in making a useful contribution. A small improvement can restore your faith that effort matters. Letting yourself enjoy what is already good can be as sustaining as noticing what still needs care.",
    Libra: "Your world opens through partnership and exchange. Another person’s perspective can reveal possibilities you would not have reached alone. Your own judgment needs a place in the conversation, even with someone you greatly admire.",
    Scorpio: "You find meaning where a difficult experience changes what you understand. You are willing to look closely at what others prefer to leave alone. Growth can also arrive quietly, without asking you to pass through another ordeal.",
    Sagittarius: "Your faith grows when you encounter a wider world. A journey or a new way of thinking can make life feel full of possibility again. Conviction stays generous when it leaves room for something you have yet to understand.",
    Capricorn: "You trust possibilities that you can help bring into being. Growth feels real when it has a foundation and somewhere to go. Some opportunities deserve a hearing before you know how to justify them.",
    Aquarius: "You find hope in what people might make possible together. A different way of living can feel worth believing in long before it is widely accepted. Your vision becomes more generous when it has room for people who do not share it yet.",
    Pisces: "Your capacity for hope is touched by things you cannot quite explain. An act of kindness can restore your sense that life holds more than its difficulties. Keeping a little discernment lets your generosity reach places where it can truly help.",
  },
  Saturn: {
    Aries: "You may feel you need permission before you can act on your own behalf. Experience teaches you to stand behind a decision without waiting for complete certainty. Courage can be something you practice in small, uncelebrated steps.",
    Taurus: "Having enough can feel like a responsibility you must never stop attending to. You learn to build security with patience and care. Over time, that foundation can give you room to loosen your hold on what you have.",
    Gemini: "You take the responsibility of being understood seriously. Doubt may keep a thought private until you are sure it can withstand a question. Your voice grows steadier through use, including the conversations where you have to revise yourself.",
    Cancer: "You may be used to holding things together when someone needs care. Learning the limits of that responsibility makes room for your own feelings. A boundary can help a home remain a place of shelter for you as well.",
    Leo: "Being seen can feel like an examination of something deeply personal. Practice gives your creative life a place to stand when confidence is absent. You can allow yourself a little pleasure in expression before you know whether it is good.",
    Virgo: "You feel responsible for the details others might overlook. Patience can turn that seriousness into a reliable craft. Learning when the work is finished helps you keep your care from becoming a demand nothing can satisfy.",
    Libra: "You take promises and the obligations between people seriously. Experience teaches you that fairness includes what you can reasonably give. A lasting bond needs room for an honest limit as well as a willing commitment.",
    Scorpio: "Trust may ask you to loosen a hold that once kept you safe. You have patience for the slow work of learning what can be shared. Keeping a boundary and letting someone come close can belong to the same act.",
    Sagittarius: "You want beliefs that can bear the weight of experience. Questioning what you once accepted can feel like losing your direction. A conviction you have examined may become a steadier companion than an answer you were afraid to doubt.",
    Capricorn: "You have a strong sense of what an undertaking will ask of you. Responsibility can become a craft, practiced with patience and self-respect. Learning what is yours to carry also means learning which burdens you can put down.",
    Aquarius: "You take the future you imagine seriously enough to work for it. Giving an unusual idea a durable form asks for patience with the present. The structures you build need room for people to surprise you.",
    Pisces: "You are learning to give a boundary to things that can feel endless. A regular practice can hold a dream, or make a difficult feeling easier to bear. You can care deeply without making yourself responsible for every sorrow you encounter.",
  },
};
